version: '3.7'

services:

  usuarios:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5005:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=sistema.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@usuarios-db:5432/usuarios_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@usuarios-db:5432/usuarios_teste
    depends_on:
      - usuarios-db

  usuarios-db:
    build:
      context: ./sistema/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres